### ISSUE TITLE
Build Command Reporting Error

### ISSUE THREAD

**Issue by 524119574** [project-serum/serum-dex#1]
Hi I am trying to build the DEX. I ran the following:
```
./do.sh build dex
```

However it's telling me:
```
$ ./do.sh build dex
Building /home/wangge/serum-dex/dex
+ [[ -n '' ]]
+ cargo install xargo
    Updating crates.io index
     Ignored package `xargo v0.3.22` is already installed, use --force to override
+ xargo --version
+ rustc --print sysroot
/home/wangge/.rustup/toolchains/stable-x86_64-unknown-linux-gnu
+ set +e
+ rustup toolchain uninstall bpf
info: no toolchain installed for 'bpf'
+ set -e
+ rustup toolchain link bpf rust-bpf
error: not a directory: 'rust-bpf/lib'
```
Any idea why?

**Comment by 524119574** [comment]
I didn't really solve this. But as a workaround, [this](https://github.com/serum-community/serum-dex/blob/master/) is quite helpful.

**Comment by sconybeare** [comment]
There was an undocumented step in the build: you need to run `./do.sh update` at least once. That step is in the first-time-setup section of the README now, thanks for pointing this out!
