### ISSUE TITLE
What does `[u64; 4]` mean?

### ISSUE THREAD

**Issue by secretshardul** [project-serum/serum-dex#141]
Several structs use the type `[u64; 4]` for what I suspect is the public key.  For instance in [MarketState](https://github.com/project-serum/serum-dex/blob/7d1d41538417aa8721aabea9503bf9d99eab7cc4/dex/src/state.rs#L74) and [LeafNode](https://github.com/project-serum/serum-dex/blob/7d1d41538417aa8721aabea9503bf9d99eab7cc4/dex/src/critbit.rs#L57).

```rs
pub struct MarketState {
    // 0
    pub account_flags: u64, // Initialized, Market

    // 1
    pub own_address: [u64; 4],

    // 5
    pub vault_signer_nonce: u64,
    // 6
    pub coin_mint: [u64; 4],
    // 10
    pub pc_mint: [u64; 4],

    // 14
    pub coin_vault: [u64; 4],
    
```

```rs
pub struct LeafNode {
    tag: u32,
    owner_slot: u8,
    fee_tier: u8,
    padding: [u8; 2],
    key: u128,
    owner: [u64; 4],
    quantity: u64,
    client_order_id: u64,
}
```

My use case is specifically to:
1. check if a market's `coin_mint` matches the address of a program account; and to
2. find public key used for placing a serum order, from `owner` field in LeafNode.

**Comment by skynetcapital** [comment]
You should be able to use it as a Rust `Pubkey`, using the `Pubkey::new` constructor.

Example: https://github.com/project-serum/serum-dex/blob/master/assert-owner/src/lib.rs#L12
```rust
let pubkey = Pubkey::new(instruction_data);
```

I could be wrong though.

**Comment by secretshardul** [comment]
`Pubkey::new()` takes in a parameter of type `&[u8]` (byte array), so this doesn't work directly. I'll try converting `[u64; 4]` into this format and see.

**Comment by secretshardul** [comment]
Gotcha, this should be in the SDK.

```rs
let mut address_vector: Vec<u8> = vec![];
for address_unit in market_data.bids.iter() {
    let converted_address_unit = address_unit.to_le_bytes();
    address_vector.extend(converted_address_unit.iter());
}
let bids_pubkey = Pubkey::new(&address_vector[..]);
```

But interested in knowing why `[u64; 4]` format was used instead of `&[u8]` for storage.

**Comment by armaniferrante** [comment]
Correct that [u64; 4] is for Pubkeys. Closing as there's no action item here.
