### ISSUE TITLE
Bug: Bids fail silently for large limit prices

### ISSUE THREAD

**Issue by secretshardul** [project-serum/serum-dex#146]
Bids/buy orders don't show up on the slab data structure when a large limit price is set. However the order instruction goes through without panicking. This happens for prices around  100_000 and higher.

Whereas I'm able to place asks/sell orders with `u64::MAX` without issues.

```rs
dex::new_order_v3(
    ctx,
    side.into(),
    NonZeroU64::new(100_000).unwrap(),\
    NonZeroU64::new(max_coin_qty).unwrap(),
    NonZeroU64::new(max_native_pc_qty).unwrap(),
    SelfTradeBehavior::DecrementTake,
    OrderType::Limit,
    client_order_id,
    limit,
)
```

To read slab data, I'm using the code below. It works properly for smaller values.
```rs
let bids_slab = market_data.load_bids_mut(&ctx.accounts.market_accounts.bids)?;
msg!("Smallest bid: {:?}", bids_slab.find_min());
msg!("Largest bid: {:?}", bids_slab.find_max());
// Read data
```

Log output:
```
Program log: Smallest bid: None
Program log: Largest bid: None
```

**Comment by armaniferrante** [comment]
I am currently unable to reproduce.

**Comment by secretshardul** [comment]
Closed. As order sizes are only stored in coin, bid sizes should be a multiple of limit price. Less than that, orders fail.
