### ISSUE TITLE
Funds lost during SBR/USDC transaction

### ISSUE THREAD

**Issue by romanzac** [project-serum/serum-dex#171]
Hi there,

Everything looks fine at transaction level, however at the last step when USDC should be deposited nothing happened.

https://solscan.io/tx/MBSGuPcDa1X6yb1vNTG7WszXS99YUa8V4nCw6igmoSiDd8yi4hu6Z6em61XGuK9VtdvqignuEVK9Ky66PvKfBib

**Comment by armaniferrante** [comment]
It appears you created a new order. You need to either wait for the order to get filled or cancel it. At which point one can "settle" back to one's wallet.

**Comment by armaniferrante** [comment]
If you haven't already, and if this isn't a dev related issue, please join the Discord for further assistance https://discord.gg/venBPvbh.

**Comment by romanzac** [comment]
I've got my USDC. Thanks.
