### ISSUE TITLE
Tokens remain in Vault after SettleFunds is executed

### ISSUE THREAD

**Issue by PraetorP** [project-serum/serum-dex#199]
I am writing a client (in Rust) to interact with Serum. When testing@devnet it (a simple case when two participants place Asks / Bids orders with an exchange rate of 1:1), I encountered a problem that the Ask side funds (pc token) are not returned to the account even after the `SettleFunds` instruction has been executed. In this case, the proceeds from the sale of coin tokens pc tokens are stored in the vault. Thus, for payer / wallet # 1 we have the following balance (after order execution and `SettleFunds`) -1 coin, for payer / wallet # 2: -1 pc, +1 coin.

P.S> Do you plan to develop a client library for Rust (similar to `serum-ts`) ?

###### Before order placement
![image](https://user-images.githubusercontent.com/45266194/144564772-30a3370c-f55b-4745-8364-90aff68d7ea4.png)
![image](https://user-images.githubusercontent.com/45266194/144564702-f40b23e5-61e4-47b1-a5d1-1b7cfcc7788d.png)
###### State after orders execution and `SettleFunds`
![image](https://user-images.githubusercontent.com/45266194/144565031-66a87f6a-be12-4e81-a89d-50cbcc749d36.png)

###### `SettleFunds` logs for payer#1 
![image](https://user-images.githubusercontent.com/45266194/144565543-bfb005ef-2f40-49d8-bf6f-461beb8ae584.png)
###### `SettleFunds` logs for payer#2
![image](https://user-images.githubusercontent.com/45266194/144565705-ce0f9a85-f621-4705-80f8-5d5aaa43d04c.png)
###### Vault
![image](https://user-images.githubusercontent.com/45266194/144567472-8af1746a-b09d-4f20-9bc2-608fb6df1412.png)

###### Market Info
``` 
own_address:    7KH444DFaHsnJECWhmLe3VYhqSn8XY2RtxPrsLS92rhS
coin_mint:      9ZpZqwJfDQzppXkazKBTqNFW1z4rLL9wxbkbhPbWTb3n
pc_mint:        G5JuS6p1TX7P3dz2DhiQ1L1exERem6Ayn5ZwqXx29dkn
coin_vault:     8h8yreygpuRiwqhRwzGFNdrNT7P9qx9f9HADyzxZrJvY
pc_vault:       HiX9rBut3LU5P3GwT2aR8uC1co6gKRjM5UYtcPZHca7j
req_q:          EXeDheqgB8dQLN7NYrUn6zwm6Cg6Z21LLXxb9xvWRfTR
event_q:        FR6Gn5HHNG8i4au62ec7hA1RnsBSXS1SMFCiTtKj6qdq
bids:           5Fm4HGTVeRsttjM3oSPVuyUq5awLdbTT5UtpmCwMghwM
asks:           CamnzxFGMKCszpUgHsYipHh9YTag3TeXSWtnqvqiDdn8
coin_lot_size:  100000
pc_lot_size:    100
pc_decimal:     9
coin_decimal:   9
```
###### Payers/wallet Info
```
wallet #1 addres: BXhe2cKFT6UEF5gLiHCDJnqQVxyKVsjnH95m3AaCDCRc
wallet #1 pc addres: 3dhhuqUTq2oQxh4Lhz1zyeJoUnip31LWUK6sWvccyptL
wallet #1 coin addres: 5f9UiFcVPnK1u2k9sHW4Qqx6kesbpBLrVfSBCRujK5h6

wallet #2 addres: 857hQyZViutfWSSUj5HL1oxJP5goBHTvzAMNWCQpg9Z7
wallet #2 pc addres: 2UiNCsmECibXM4AW7ePGe7zFQkxoAtfGsGWX6jn6iuRU
wallet #2 coin addres: CSYU2V943K4ZPEvwLRZvPDaFumVjaZ4Sht3UKe3WNy5o
```
###### Additional Info
![image](https://user-images.githubusercontent.com/45266194/144567240-79802b9c-6080-4676-be93-48a3bba3201f.png)

**Comment by beepsaidblue** [comment]
Hi @PraetorP same issue here. To be precise, I observed that for any maker sell / buy order, the maker does not receive  proceeds after transaction settles. Order settles fine with taker. Did you manage to resolve this issue?

**Comment by PraetorP** [comment]
> Hi @PraetorP same issue here. To be precise, I observed that for any maker sell / buy order, the maker does not receive proceeds after transaction settles. Order settles fine with taker. Did you manage to resolve this issue?

Hi @beepsaidblue! Yes, I found a solution. I wanted to close the issue, but I saw your message :) . If you have your own test market, then you need to run crank for it or make your own approach to processing the event queue (with calling the consume events ix).

**Comment by beepsaidblue** [comment]
@PraetorP Could you point me to any sample code for how to do cranking?
