### ISSUE TITLE
Pubkey seeds

### ISSUE THREAD

**Issue by saman-pasha** [project-serum/serum-dex#226]
hi i want to initialize a market but the function gets many pubkeys that i dont know how to create them
```
pub fn initialize_market(
    market: &Pubkey,
    program_id: &Pubkey,
    coin_mint_pk: &Pubkey,
    pc_mint_pk: &Pubkey,
    coin_vault_pk: &Pubkey,
    pc_vault_pk: &Pubkey,
    authority_pk: Option<&Pubkey>,
    prune_authority_pk: Option<&Pubkey>,
    consume_events_authority_pk: Option<&Pubkey>,
    // srm_vault_pk: &Pubkey,
    bids_pk: &Pubkey,
    asks_pk: &Pubkey,
    req_q_pk: &Pubkey,
    event_q_pk: &Pubkey,
    coin_lot_size: u64,
    pc_lot_size: u64,
    vault_signer_nonce: u64,
    pc_dust_threshold: u64,
)
```
I need to create them to pass them to this function,
`spl-associated-token-address` has a format for seeds to generate pubkeys.
is there any function which could generate these pubkeys?

**Comment by saman-pasha** [comment]
after many tries i got an error during `initialize_mint`
```"Program DESVgJVGajEgKGXhb6XmqDHGz3VjdgP7rEVESBgxmroY failed: custom program error: 0x1000633"```
Can you tell me what is this error?

**Comment by saman-pasha** [comment]
resolved. the problem was owner of vault accounts

**Comment by nevi-me** [comment]
Hi @saman-pasha, I'm having the same issue. How exactly did you resolve it on your side? I see that the error is in a mismatch of the vault owner key vs what's expected, but I can't see what exactly I'm doing that's wrong.

```rust
// check that the vaults are owned by the market's withdrawal authority key
let vault_data = vault.0.try_borrow_data()?;
let vault_owner = array_ref![vault_data, 0x20, 0x20];
println!("vault owner: {}, owner key bytes: {}", Pubkey::new_from_array(*vault_owner), Pubkey::new_from_array(vault_owner_key_bytes));
check_assert_eq!(vault_owner, &vault_owner_key_bytes)?;
```

Output:

```
vault owner: 11111111111111111111111111111111, owner key bytes: ACwG6En1BLxLp8pJagruzv82NwEmHUa8PKHekkfvXQag
```

**Comment by nevi-me** [comment]
For anyone else who encounters this issue, the solution is to use `serum_dex::state::gen_vault_signer_key;`. I had implemented the seeds manually by looking at the code, but was getting an error.
