### ISSUE TITLE
Js-SDK

### ISSUE THREAD

**Issue by AnasSaeed123** [project-serum/serum-dex#31]
Is there any js-sdk of serum coin available for transaction?

I want to integrate it into OPOLO hardware wallet.

**Comment by armaniferrante** [comment]
Have you checked out https://github.com/project-serum/serum-js and https://github.com/solana-labs/solana-web3.js/ ?

**Comment by armaniferrante** [comment]
Closing this issue. Let's take this conversation into Discord, please. https://discord.com/channels/739225212658122886/752530209848295555
