### ISSUE TITLE
settle_funds return 0 usdt to my address

### ISSUE THREAD

**Issue by cryptoalert15** [project-serum/serum-dex#74]
sol address:7ewn8oj7MWyhZE5qFux1npzUnuT4XCVvBvYiMHehYvBb
usdt address:8pkzuX9GjrgEFuX4JXQeV4hcSjwTba59yC92vSfbz45H
fida address:4BCnuuQXHXEMiUVYYA7mw2Jc5AyX5q1FcTRDmvnV9uDR

i submit an order https://explorer.solana.com/tx/522X9qN66UMbSoLk5Sry9iRcm9zFFoaR1M34qysJSedtCQ5893ofNhxx61uaqnRxj4b8cadfXH4YEM1BV1Bd3WKP , then i've cancelled it twice , not sure why.. https://explorer.solana.com/tx/54GUkmszRxT9g8T9GFL2PZRyi8Z6PDKzmT5STkVVbGcHoQRgRNC6HUeChTuggKDdmFsn1GM6WLHrbx3MeQJVAHfZ and https://explorer.solana.com/tx/46XJr3zDs94tmDNgjXHhQJTYFQfPnjyKKrzrRtYcWYNJ9672zEiv9XxZZsmuHj2h3N1fnNVfMA5po8K1QLe1zhvb

then not sure what i did there when i've tried to settle_my funds https://explorer.solana.com/tx/2ph3m68QKaxjyyk2SmBQ2m2j6XF7ksYjMiz9hVo9eo5toKhPopQRj8XT6AA8AdPUXBNEo39cy5zf91WHYC8i2WMS

`open_orders_account = market.find_open_orders_accounts_for_owner(owner_address=PublicKey('7ewn8oj7MWyhZE5qFux1npzUnuT4XCVvBvYiMHehYvBb'))`
but when i do now `settle_funds `it sends me 0 usdt back all the time
https://explorer.solana.com/tx/36Rca4VQQe7dodh2VTavXRTPJZGQuknhc4wRt4ST2s8GgQijbFJKwmoDsxgBJnHYrutKQzzCuQtuRc41mfPzUSeZ and https://explorer.solana.com/tx/4gJyqXLH7Xr4XcfwsTjgbjDbFBasHhQjaPjBwkxAk8Cd9hU92xqUHgw2sbRGcP3KonCrFu3PFADF6CoE5PYLHFa4
![image](https://user-images.githubusercontent.com/52983648/102916027-87895780-448b-11eb-85d3-0152e8d5b8cb.png)

please dm me on dicord `cryptoguy100786#0098`

how to get my usdt from of https://explorer.solana.com/address/Dygr7hmVgydf6Cs4CF34EbXbD8xhJJVMXjvYJCR7LqmM ? thanks

**Comment by armaniferrante** [comment]
The problem here is that [settle_funds](https://explorer.solana.com/tx/2ph3m68QKaxjyyk2SmBQ2m2j6XF7ksYjMiz9hVo9eo5toKhPopQRj8XT6AA8AdPUXBNEo39cy5zf91WHYC8i2WMS) was called with the destination "Quote wallet" set as the open order's [vault](https://explorer.solana.com/address/Dygr7hmVgydf6Cs4CF34EbXbD8xhJJVMXjvYJCR7LqmM) now owns those funds.

**Comment by armaniferrante** [comment]
Thanks for the issue @cryptoalert15. This is the same problem as https://github.com/project-serum/serum-dex/issues/53, so will be closing this in favor of the original issue.

Will continue contact over Discord and/or in that issue.

**Comment by cryptoalert15** [comment]
> The problem here is that [settle_funds](https://explorer.solana.com/tx/2ph3m68QKaxjyyk2SmBQ2m2j6XF7ksYjMiz9hVo9eo5toKhPopQRj8XT6AA8AdPUXBNEo39cy5zf91WHYC8i2WMS) was called with the "Quote wallet" set as the open order's [vault](https://explorer.solana.com/address/Dygr7hmVgydf6Cs4CF34EbXbD8xhJJVMXjvYJCR7LqmM), which now owns those funds.

indeed, but also before same vault https://explorer.solana.com/address/Dygr7hmVgydf6Cs4CF34EbXbD8xhJJVMXjvYJCR7LqmM owns those funds ...

**Comment by cryptoalert15** [comment]
> Thanks for the issue @cryptoalert15. This is the same problem as #53, so will be closing this in favor of the original issue.
> 
> Will continue contact over Discord and/or in that issue.

thanks again for investigation, let's hope there will be a way to fix it because amount is huge :(
