### ISSUE TITLE
Testing of the pool software?

### ISSUE THREAD

**Issue by PaulBernier** [project-serum/serum-dex#83]
Hi, as I potentially intend to use/extend the pool program, I would like to know how the testing has been performed. I see a few simple unit tests in the `context.rs` file and that's it. Is there any integration tests? Was there end to end testing? Thank you
cc @garywang @sconybeare

**Comment by sconybeare** [comment]
A bunch of manual testing was done with the gui, in addition to those tests in `context.rs`. That's it as far as I know.

**Comment by armaniferrante** [comment]
Nothing actionable to do here. I don't think there's any plans for continued work on the current pool program. Closing. Please re-open if I am mistaken.
