### ISSUE TITLE
certain account type markets

### ISSUE THREAD

**Issue by marbar3778** [project-serum/serum-dex#98]
## Summary

When trading a derivative, for example a perpetual swap, a user can not use their normal spot trading account, they would need to use a margin trading account. Currently, within Serum there is no way to limit what sort of accounts can trade in which markets.

Ideally there would be a way to tell a market to only accept trades from a certain account type. 

I haven't looked at the code behind serum so not sure what this would entail.

**Comment by armaniferrante** [comment]
Permissioned markets will allow one to limit what accounts can trade on a market. https://github.com/project-serum/serum-dex/pull/150

**Comment by armaniferrante** [comment]
Done by #150 and the prs linked from there.
